import { db } from "../server/db";
import { items, businessPartners } from "../shared/schema";
import { eq } from "drizzle-orm";

type ItemSeed = {
  sku: string;
  name: string;
  itemRole: string;
  itemType: string;
  isActive: string;
  isEgg: boolean;
  eggContentType: string | null;
  primaryGrade: number | null;
  secondaryGrade: number | null;
  minPrimary: number | null;
  eggsPerPack: number | null;
  basketSku: string | null;
  basketUnit: string | null;
  eggsPerBasket: number | null;
  packPerBasket: number | null;
  sellingUnit: string | null;
  baseUnit: string | null;
  isSellable: boolean;
  isProducable: boolean;
  isConsumable: boolean;
  partnerCode: string | null;
};

const itemsData: ItemSeed[] = [
  // === RAW MATERIAL ===
  { sku: "10000", name: "ไข่คละ", itemRole: "RM", itemType: "raw_egg", isActive: "active", isEgg: true, eggContentType: "UNGRADED_EGG", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: false, isProducable: false, isConsumable: true, partnerCode: null },

  // === DEFECT ===
  { sku: "10101", name: "ไข่ตกเกรด - บาง", itemRole: "DEFECT", itemType: "thin_shell", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10102", name: "ไข่ตกเกรด - บุบ", itemRole: "DEFECT", itemType: "cracked_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10103", name: "ไข่ตกเกรด - เปื้อน", itemRole: "DEFECT", itemType: "dirty_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10104", name: "ไข่แตกน้ำไหล", itemRole: "DEFECT", itemType: "cracked_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10105", name: "ไข่คัดสูญเสีย", itemRole: "DEFECT", itemType: "unusable", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: false, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10106", name: "ไข่แตกน้ำไหล/บาง", itemRole: "DEFECT", itemType: "cracked_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10107", name: "ไข่แตกน้ำไหล/บุบ", itemRole: "DEFECT", itemType: "cracked_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },
  { sku: "10108", name: "ไข่แตกน้ำไหล/เปื้อน", itemRole: "DEFECT", itemType: "cracked_egg", isActive: "active", isEgg: true, eggContentType: "UNDERGRADE", primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: 1, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ฟอง", baseUnit: "ฟอง", isSellable: true, isProducable: false, isConsumable: true, partnerCode: null },

  // === GENERIC FG - PACK 4 ===
  { sku: "30001", name: "ไข่ไก่เบอร์ 0 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30101", name: "ไข่ไก่เบอร์ 1 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30201", name: "ไข่ไก่เบอร์ 2 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30301", name: "ไข่ไก่เบอร์ 3 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30401", name: "ไข่ไก่เบอร์ 4 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30501", name: "ไข่ไก่เบอร์ 5 บรรจุ 4 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },

  // === GENERIC FG - PACK 10 ===
  { sku: "30002", name: "ไข่ไก่เบอร์ 0 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30102", name: "ไข่ไก่เบอร์ 1 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30202", name: "ไข่ไก่เบอร์ 2 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30302", name: "ไข่ไก่เบอร์ 3 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30402", name: "ไข่ไก่เบอร์ 4 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30502", name: "ไข่ไก่เบอร์ 5 บรรจุ 10 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },

  // === GENERIC FG - PACK 15 ===
  { sku: "30003", name: "ไข่ไก่เบอร์ 0 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30103", name: "ไข่ไก่เบอร์ 1 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30203", name: "ไข่ไก่เบอร์ 2 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30303", name: "ไข่ไก่เบอร์ 3 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30403", name: "ไข่ไก่เบอร์ 4 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30503", name: "ไข่ไก่เบอร์ 5 บรรจุ 15 ฟอง/แพ็ค", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: null },

  // === GENERIC WIP - TRAY 30 (single grade) ===
  { sku: "30004", name: "ไข่ไก่เบอร์ 0 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30104", name: "ไข่ไก่เบอร์ 1 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30204", name: "ไข่ไก่เบอร์ 2 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30304", name: "ไข่ไก่เบอร์ 3 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30404", name: "ไข่ไก่เบอร์ 4 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30504", name: "ไข่ไก่เบอร์ 5 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "30604", name: "ไข่ไก่เบอร์ 6 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 6, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },

  // === GENERIC WIP - TRAY 30 (mixed grade) ===
  { sku: "32304", name: "ไข่ไก่เบอร์ 2-3 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 2, secondaryGrade: 3, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },
  { sku: "33404", name: "ไข่ไก่เบอร์ 3-4 บรรจุ 30 ฟอง/ถาด", itemRole: "WIP", itemType: "graded_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: false, isProducable: true, isConsumable: false, partnerCode: null },

  // === BIG C (B0xxx) ===
  { sku: "B0001", name: "ไข่ไก่คละ (10ฟอง) ตราบิ๊กซี (7แพ็ค/กระกร้า) - mini", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 10, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 70, packPerBasket: 7, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0002", name: "ไข่ไก่คละ (30ฟอง) ตราบิ๊กซี (2ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 60, packPerBasket: 2, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0003", name: "ไข่ไก่คละ (30ฟอง) ตราบิ๊กซี (6ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0004", name: "ไข่ไก่คละขนาด 2+3 (30ฟอง) ตราบิ๊กซี (6ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 2, secondaryGrade: 3, minPrimary: 40, eggsPerPack: 30, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0005", name: "ไข่ไก่เบอร์ 0 แพ็ค 10 ฟอง ตราบิ๊กซี (14แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 140, packPerBasket: 14, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0006", name: "ไข่ไก่เบอร์ 1 แพ็ค 10 ฟอง ตราบิ๊กซี (14แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 140, packPerBasket: 14, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0007", name: "ไข่ไก่เบอร์ 1 แพ็ค 10 ฟอง ตราบิ๊กซี (7แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 70, packPerBasket: 7, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0008", name: "ไข่ไก่เบอร์ 1 แพ็ค 4 ฟอง ตราบิ๊กซี (6แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: "B1BC00001", basketUnit: "กะทัด", eggsPerBasket: 24, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0009", name: "ไข่ไก่เบอร์ 2 (30ฟอง) ตราบิ๊กซี (2ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 60, packPerBasket: 2, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0010", name: "ไข่ไก่เบอร์ 2 แพ็ค 10 ฟอง ตราบิ๊กซี (7แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 70, packPerBasket: 7, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0011", name: "ไข่คละเบอร์ 2+3 แพ็ค 10 ฟอง ตราบิ๊กซี (14แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 2, secondaryGrade: 3, minPrimary: 40, eggsPerPack: 10, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 140, packPerBasket: 14, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0012", name: "ไข่ไก่คละเบอร์ 3-4 แพ็ค 10 ฟอง ตราบิ๊กซี (7แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 10, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 70, packPerBasket: 7, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0013", name: "ไข่ไก่เบอร์ 4 (30ฟอง) ตราบิ๊กซี Mini (2ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1BC00002", basketUnit: "กะทัด", eggsPerBasket: 60, packPerBasket: 2, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0014", name: "ไข่ไก่เบอร์ 0 (30ฟอง) ตราบิ๊กซี (6ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0015", name: "ไข่ไก่เบอร์ 1 (30ฟอง) ตราบิ๊กซี (6ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0016", name: "ไข่ไก่เบอร์ 3 (30ฟอง) ตราบิ๊กซี (6ถาด/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },
  { sku: "B0017", name: "ไข่ไก่เบอร์ 3 แพ็ค 10 ฟอง ตราบิ๊กซี (14แพ็ค/กระกร้า)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1BC00003", basketUnit: "กะทัด", eggsPerBasket: 140, packPerBasket: 14, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "BC" },

  // === CJ (C0xxx) ===
  { sku: "C0001", name: "ยกนิ้วไข่ไก่ขนาด S แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 4, secondaryGrade: 5, minPrimary: 40, eggsPerPack: 30, basketSku: "B1CJ00001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "CJ" },
  { sku: "C0002", name: "ยกนิ้วไข่ไก่ขนาด M แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: "B1CJ00001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "CJ" },
  { sku: "C0003", name: "ยกนิ้วไข่ไก่ขนาด L แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 30, basketSku: "B1CJ00001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "CJ" },
  { sku: "C0004", name: "ยกนิ้วไข่ไก่สดเบอร์ 2 แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: "B1CJ00001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 6, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "CJ" },

  // === MAKRO / ARO (M0xxx) ===
  { sku: "M0001", name: "ARO ไข่ไก่คละเบอร์ 3-4 มีฝา 30ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0002", name: "ARO ไข่ไก่คละเบอร์ 3-4 ไม่มีฝา 30ฟองx5", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "มัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0003", name: "ARO ไข่ไก่เบอร์ 0 (10ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0004", name: "ARO ไข่ไก่ เบอร์ 0 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0005", name: "ARO ไข่ไก่เบอร์ 1 (10ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0006", name: "ARO ไข่ไก่ เบอร์ 1 แพ็ค 15 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 12, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0007", name: "ARO ไข่ไก่ เบอร์ 1 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0008", name: "ARO ไข่ไก่เบอร์ 2 (10ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0009", name: "ARO ไข่ไก่ เบอร์ 2 แพ็ค 15 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 15, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 180, packPerBasket: 12, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0010", name: "ARO ไข่ไก่ เบอร์ 2 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0011", name: "ARO ไข่ไก่ เบอร์ 2 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0012", name: "ARO ไข่ไก่เบอร์ 2 ไม่มีฝา 30ฟองx5", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "มัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0013", name: "ARO ไข่ไก่เบอร์ 3 (10ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0014", name: "ARO ไข่ไก่ เบอร์ 3 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0015", name: "ARO ไข่ไก่เบอร์ 3 ไม่มีฝา 30ฟองx5", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "มัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0016", name: "ARO ไข่ไก่เบอร์ 4 (10ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0017", name: "ARO ไข่ไก่เบอร์ 4 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0018", name: "ARO ไข่ไก่เบอร์ 4 ไม่มีฝา 30ฟองx4", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "มัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0019", name: "ARO ไข่ไก่เบอร์ 5 ไม่มีฝา 30ฟองx4", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "มัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0020", name: "ARO ไข่ไก่เบอร์ 4 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0021", name: "ARO ไข่ไก่เบอร์ 3 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0022", name: "ARO ไข่ไก่เบอร์ 3 (12 ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 12, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },
  { sku: "M0023", name: "ARO ไข่ไก่คละเบอร์ 3-4 (10 ฟอง/แพ็ค)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 10, basketSku: "B1MK0001", basketUnit: "กะทัด", eggsPerBasket: 200, packPerBasket: 20, sellingUnit: "กะทัด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MK" },

  // === MSP-EGGS (S0xxx) - all 30-egg trays ===
  { sku: "S0001", name: "MSP-EGGS ไข่ไก่เบอร์ 0 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0002", name: "MSP-EGGS ไข่ไก่เบอร์ 1 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0003", name: "MSP-EGGS ไข่ไก่เบอร์ 2 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0004", name: "MSP-EGGS ไข่ไก่เบอร์ 3 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0005", name: "MSP-EGGS ไข่ไก่เบอร์ 4 มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0006", name: "MSP-EGGS ไข่ไก่เบอร์ 0 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0007", name: "MSP-EGGS ไข่ไก่เบอร์ 1 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0008", name: "MSP-EGGS ไข่ไก่เบอร์ 2 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0009", name: "MSP-EGGS ไข่ไก่เบอร์ 3 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },
  { sku: "S0010", name: "MSP-EGGS ไข่ไก่เบอร์ 4 ไม่มีฝา 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "MS" },

  // === THAIFOOD (T0xxx) ===
  { sku: "T0001", name: "ไข่ไก่เบอร์ 1 แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0002", name: "ไข่ไก่เบอร์ 2 แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0003", name: "ไข่ไก่เบอร์ 3 แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0004", name: "ไข่ไก่ เบอร์ M แพ็ค 10 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0005", name: "ไข่ไก่ เบอร์ L แพ็ค 10 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0006", name: "ไข่ไก่เบอร์ M แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },
  { sku: "T0007", name: "ไข่ไก่เบอร์ L แพ็ค 30 ฟอง", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "TF" },

  // === MOTHER'S EGG (O0xxx) ===
  { sku: "O0001", name: "Mother's Egg เบอร์ 0 (แพ็ค 4ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0002", name: "Mother's Egg เบอร์ 0 (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0004", name: "Mother's Egg เบอร์ 0 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0101", name: "Mother's Egg เบอร์ 1 (แพ็ค 4ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0102", name: "Mother's Egg เบอร์ 1 (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0104", name: "Mother's Egg เบอร์ 1 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0201", name: "Mother's Egg เบอร์ 2 (แพ็ค 4ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0202", name: "Mother's Egg เบอร์ 2 (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0204", name: "Mother's Egg เบอร์ 2 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0301", name: "Mother's Egg เบอร์ 3 (แพ็ค 4ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0302", name: "Mother's Egg เบอร์ 3 (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0304", name: "Mother's Egg เบอร์ 3 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0402", name: "Mother's Egg เบอร์ 4 (แพ็ค 4ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 4, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0404", name: "Mother's Egg เบอร์ 4 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O0504", name: "Mother's Egg เบอร์ 5(S) (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O1202", name: "Mother's Egg เบอร์ 1,2(L) (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O1204", name: "Mother's Egg เบอร์ 1,2(L) (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O3402", name: "Mother's Egg เบอร์ 3,4(M) (แพ็ค 10ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 10, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "แพ็ค", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },
  { sku: "O3404", name: "Mother's Egg เบอร์ 3-4 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "ME" },

  // === LOTUS'S (L0xxx) ===
  { sku: "L0004", name: "Lotus's เบอร์ 0 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 0, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L0104", name: "Lotus's เบอร์ 1 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 1, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L0204", name: "Lotus's เบอร์ 2 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 2, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L0304", name: "Lotus's เบอร์ 3 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 3, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L0404", name: "Lotus's เบอร์ 4 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 4, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L0504", name: "Lotus's เบอร์ 5 (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L1204", name: "Lotus's เบอร์ 1-2(L) (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 1, secondaryGrade: 2, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L3404", name: "Lotus's เบอร์ 3-4(M) (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_MIX", primaryGrade: 3, secondaryGrade: 4, minPrimary: 40, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },
  { sku: "L5004", name: "Lotus's เบอร์ 5(S) (แพ็ค 30ฟอง)", itemRole: "FG", itemType: "packed_egg_OEM", isActive: "active", isEgg: true, eggContentType: "GRADED_SINGLE", primaryGrade: 5, secondaryGrade: null, minPrimary: null, eggsPerPack: 30, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ถาด", baseUnit: "ฟอง", isSellable: true, isProducable: true, isConsumable: false, partnerCode: "LT" },

  // === PACKAGING - BASKETS ===
  { sku: "B1BC00001", name: "กะทัด BigC A", itemRole: "PACKAGING", itemType: "basket", isActive: "active", isEgg: false, eggContentType: null, primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: null, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ใบ", baseUnit: "ใบ", isSellable: false, isProducable: false, isConsumable: true, partnerCode: "BC" },
  { sku: "B1BC00002", name: "กะทัด BigC S", itemRole: "PACKAGING", itemType: "basket", isActive: "active", isEgg: false, eggContentType: null, primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: null, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ใบ", baseUnit: "ใบ", isSellable: false, isProducable: false, isConsumable: true, partnerCode: "BC" },
  { sku: "B1BC00003", name: "กะทัด BigC M", itemRole: "PACKAGING", itemType: "basket", isActive: "active", isEgg: false, eggContentType: null, primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: null, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ใบ", baseUnit: "ใบ", isSellable: false, isProducable: false, isConsumable: true, partnerCode: "BC" },
  { sku: "B1CJ00001", name: "กะทัด ซีเจ", itemRole: "PACKAGING", itemType: "basket", isActive: "active", isEgg: false, eggContentType: null, primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: null, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ใบ", baseUnit: "ใบ", isSellable: false, isProducable: false, isConsumable: true, partnerCode: "CJ" },
  { sku: "B1MK0001", name: "กะทัด Makro", itemRole: "PACKAGING", itemType: "basket", isActive: "active", isEgg: false, eggContentType: null, primaryGrade: null, secondaryGrade: null, minPrimary: null, eggsPerPack: null, basketSku: null, basketUnit: null, eggsPerBasket: null, packPerBasket: null, sellingUnit: "ใบ", baseUnit: "ใบ", isSellable: false, isProducable: false, isConsumable: true, partnerCode: "MK" },
];

async function seedItems() {
  console.log("Starting items seed...");

  // Build partner code → ID map
  const allPartners = await db.select().from(businessPartners);
  const partnerMap: Record<string, number> = {};
  for (const p of allPartners) {
    partnerMap[p.code] = p.id;
  }
  console.log(`Found ${allPartners.length} business partners`);

  let inserted = 0;

  for (const item of itemsData) {
    const partnerId = item.partnerCode ? (partnerMap[item.partnerCode] ?? null) : null;

    const updateValues = {
      name: item.name,
      itemRole: item.itemRole,
      itemType: item.itemType,
      isActive: item.isActive,
      isEgg: item.isEgg,
      isEggItem: item.isEgg,
      eggContentType: item.eggContentType,
      primaryGrade: item.primaryGrade,
      secondaryGrade: item.secondaryGrade,
      minPrimary: item.minPrimary,
      minPrimaryGrade: item.minPrimary?.toString() ?? null,
      eggsPerPack: item.eggsPerPack,
      eggsPerBasket: item.eggsPerBasket,
      packPerBasket: item.packPerBasket,
      basketSku: item.basketSku,
      basketUnit: item.basketUnit,
      sellingUnit: item.sellingUnit,
      baseUnit: item.baseUnit,
      isSellable: item.isSellable,
      isProducable: item.isProducable,
      isConsumable: item.isConsumable,
      partnerId,
    };

    // Update existing row by SKU
    const existing = await db.select({ id: items.id }).from(items).where(eq(items.sku, item.sku));
    if (existing.length > 0) {
      await db.update(items).set(updateValues).where(eq(items.sku, item.sku));
      inserted++;
    } else {
      await db.insert(items).values({ sku: item.sku, ...updateValues });
      inserted++;
    }
  }

  console.log(`Done! Updated/inserted: ${inserted} items`);
}

seedItems()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error("Seed error:", e);
    process.exit(1);
  });
